# Generated by Django 5.0.7 on 2024-08-05 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='courses',
            name='category',
            field=models.CharField(choices=[('9-Month', '9-Month'), ('3-Month', '3-Month'), ('1-Month', '1-Month')], default='', max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='courses',
            name='description',
            field=models.TextField(default='', max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='courses',
            name='final_degree',
            field=models.IntegerField(default=100),
        ),
        migrations.AddField(
            model_name='courses',
            name='last_modification',
            field=models.DateTimeField(auto_now_add=True, null=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='courses',
            name='publish_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
