# Generated by Django 5.0.7 on 2024-08-05 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_courses_category_courses_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='courses',
            name='photo',
            field=models.ImageField(default='', upload_to='images'),
            preserve_default=False,
        ),
    ]
