# Generated by Django 5.0.7 on 2024-08-06 17:27

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_alter_courses_last_modification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courses',
            name='last_modification',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
